"""
mermaid_to_psmiles.py

Parse a polymer Mermaid EGL graph (as generated by polymer_to_mermaid.py)
back into a PSMILES repeat-unit string with two * attachment points.

The EGL format contract (from polymer_to_mermaid.py):
  - Nodes:   {prefix}_{Symbol}{n}[{label}]   e.g.  B0_C1[CH2]
  - Bonds:   "---" SINGLE | "===" DOUBLE | "-.-" TRIPLE | "<-->" AROMATIC
             "===|E|" / "===|Z|" E/Z-stereo double
  - Attachment points identified by:
             TL --- {entry_node}   (left  * )
             {exit_node} --- TR    (right * )

Design:
  - Only the element symbol is read from node labels; H counts are inferred
    by RDKit SanitizeMol from connectivity and valence.  This means the model
    does NOT need to update H-count labels when adding/removing branches.
  - Aromatic bonds (<-->) are passed as BondType.AROMATIC; SanitizeMol
    perceives aromaticity and sets atom/bond flags automatically.

Round-trip test (all 50 editing task inputs should recover exactly):
    python3 mermaid_to_psmiles.py
"""

from __future__ import annotations

import re
import sys
import json
from pathlib import Path
from typing import Optional

from rdkit import Chem
from rdkit.Chem import RWMol


# ── Label → element symbol ────────────────────────────────────────────────────

# Two-letter symbols that must be matched before single-letter
_TWO_LETTER = frozenset(["Si", "Cl", "Br", "Se", "Te", "Mg", "Zn", "Fe", "Cu"])

def parse_element(label: str) -> tuple[str, int]:
    """
    Extract element symbol and formal charge from a node label.
    H counts in the label are intentionally ignored — RDKit infers them.

    Examples:
        "CH2"  → ("C",  0)
        "NH"   → ("N",  0)
        "O"    → ("O",  0)
        "N(+)" → ("N", +1)
        "Si"   → ("Si", 0)
    """
    label = label.strip()

    # Formal charge
    charge = 0
    m = re.search(r'\((\d*)([+\-])\)', label)
    if m:
        mag = int(m.group(1)) if m.group(1) else 1
        charge = mag if m.group(2) == "+" else -mag
        label = label[:m.start()]

    # Two-letter element symbols first
    for sym in _TWO_LETTER:
        if label.startswith(sym):
            return sym, charge

    # Single-letter
    if label and label[0].isupper():
        return label[0], charge

    raise ValueError(f"Cannot parse element from label: {label!r}")


# ── Bond symbol → RDKit BondType ──────────────────────────────────────────────

_BOND_MAP: dict[str, Chem.BondType] = {
    "---":     Chem.BondType.SINGLE,
    "===":     Chem.BondType.DOUBLE,
    "===|E|":  Chem.BondType.DOUBLE,
    "===|Z|":  Chem.BondType.DOUBLE,
    "-.-":     Chem.BondType.TRIPLE,
    "<-->":    Chem.BondType.AROMATIC,
}

_EDGE_RE = re.compile(
    r'^\s+(\w+)\s+'
    r'(-{3}|={3}(?:\|[EZ]\|)?|\-\.\-|<-->)'
    r'\s+(\w+)\s*$'
)

_NODE_RE = re.compile(r'^\s+(\w+)\[([^\]]+)\]\s*$')


# ── Main converter ────────────────────────────────────────────────────────────

def mermaid_to_psmiles(mermaid: str) -> Optional[str]:
    """
    Convert a polymer Mermaid EGL string back to a PSMILES repeat unit.

    Returns canonical PSMILES (with two * attachment points) or None if
    parsing/sanitization fails.
    """
    lines = mermaid.splitlines()

    # 1. Collect node declarations (skip TL / TR terminus nodes)
    nodes: dict[str, tuple[str, int]] = {}  # nid → (element, formal_charge)
    for line in lines:
        m = _NODE_RE.match(line)
        if m:
            nid, label = m.group(1), m.group(2)
            if nid in ("TL", "TR"):
                continue
            try:
                symbol, charge = parse_element(label)
                nodes[nid] = (symbol, charge)
            except ValueError:
                pass

    # 2. Collect edges and identify attachment nodes
    edges: list[tuple[str, Chem.BondType, str]] = []
    entry_nodes: set[str] = set()
    exit_nodes:  set[str] = set()

    for line in lines:
        m = _EDGE_RE.match(line)
        if not m:
            continue
        a, bond_sym, b = m.group(1), m.group(2), m.group(3)
        bt = _BOND_MAP.get(bond_sym, Chem.BondType.SINGLE)

        if a == "TL":
            entry_nodes.add(b)
        elif b == "TL":
            entry_nodes.add(a)
        elif b == "TR":
            exit_nodes.add(a)
        elif a == "TR":
            exit_nodes.add(b)
        else:
            if a in nodes and b in nodes:
                edges.append((a, bt, b))

    if not entry_nodes or not exit_nodes:
        return None

    entry_nid = next(iter(entry_nodes))
    exit_nid  = next(iter(exit_nodes))

    # 3. Build RDKit RWMol — H counts inferred by SanitizeMol
    rw = RWMol()
    nid_to_idx: dict[str, int] = {}

    for nid, (symbol, charge) in nodes.items():
        try:
            atom = Chem.Atom(symbol)
        except Exception:
            return None
        atom.SetFormalCharge(charge)
        # No explicit H — let RDKit compute from valence after sanitization
        nid_to_idx[nid] = rw.AddAtom(atom)

    # Wildcard * atoms for attachment points
    ap_left  = rw.AddAtom(Chem.Atom(0))
    ap_right = rw.AddAtom(Chem.Atom(0))

    for a, bt, b in edges:
        if a in nid_to_idx and b in nid_to_idx:
            try:
                rw.AddBond(nid_to_idx[a], nid_to_idx[b], bt)
            except Exception:
                return None

    if entry_nid not in nid_to_idx or exit_nid not in nid_to_idx:
        return None
    rw.AddBond(ap_left,  nid_to_idx[entry_nid], Chem.BondType.SINGLE)
    rw.AddBond(nid_to_idx[exit_nid], ap_right,  Chem.BondType.SINGLE)

    # 4. Sanitize
    try:
        Chem.SanitizeMol(rw)
    except Exception:
        try:
            Chem.SanitizeMol(
                rw,
                Chem.SanitizeFlags.SANITIZE_ALL
                ^ Chem.SanitizeFlags.SANITIZE_PROPERTIES,
            )
        except Exception:
            return None

    return Chem.MolToSmiles(rw)


# ── Round-trip test ───────────────────────────────────────────────────────────

def round_trip_test(questions_path: str = "chemiq_results/polymer_editing_questions.jsonl"):
    """
    Verify mermaid_to_psmiles(mermaid_graph) == canonical(input_smiles)
    for all editing task inputs.
    """
    def canon(smi):
        m = Chem.MolFromSmiles(smi)
        return Chem.MolToSmiles(m) if m else None

    records = [json.loads(l) for l in open(questions_path) if l.strip()]
    ok = fail = 0
    for rec in records:
        expected = canon(rec["input_repeat_smiles"])
        recovered = mermaid_to_psmiles(rec["mermaid_graph"])
        if recovered and canon(recovered) == expected:
            ok += 1
        else:
            fail += 1
            print(f"  FAIL  {rec['name']}")
            print(f"    original : {rec['input_repeat_smiles']}  →  {expected}")
            print(f"    recovered: {recovered}")

    print(f"\nRound-trip: {ok}/{ok+fail} passed  ({fail} failures)")
    return fail == 0


if __name__ == "__main__":
    success = round_trip_test()
    sys.exit(0 if success else 1)

